# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ArtCraft.PhotoCraft
PackageVersion: 0.3.0
InstallerType: msi
ReleaseDate: 2026-10-07
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/storytold/photocraft/releases/download/v0.3.0/photocraft-0.3.0-windows-x64.msi
    InstallerSha256: 2B3E1BFDACFB597C1CAB783C9ED14ED59854CC4BF11F333973D1C823D77E9DB6
  - Architecture: x86
    InstallerUrl: https://github.com/storytold/photocraft/releases/download/v0.3.0/photocraft-0.3.0-windows-x86.msi
    InstallerSha256: 7294CCE12465D9755B776F1C558050367C49C795AF84FBA28E4428F73404D18F
  - Architecture: arm64
    InstallerUrl: https://github.com/storytold/photocraft/releases/download/v0.3.0/photocraft-0.3.0-windows-arm64.msi
    InstallerSha256: 990A6C05A5A3DE92ED4E1410546624DB8F1EB696589DB15BEECA730E268D1316
ManifestType: installer
ManifestVersion: 1.12.0
